language: node_js
node_js:
  - 0.10

before_script:
  - npm install -g grunt-cli
  - npm install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - grunt   # start a Web server
  - sleep 3

script:
  - grunt karma:unit
  - grunt karma:e2e
